[package]
name = "test-util"
version = "0.1.0"
edition = "2021"

[dependencies]
fastcrypto = "0.1.4"
rand = "0.8.5"
tempdir = "0.3.7"
ark-bw6-761 = "0.3.0"

config = { path = "../config" }
messages = { path = "../messages" }
authority = { path = "../authority" }