[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
thiserror = "1.0.30"
serde_json = "1.0.75"
fastcrypto = { version = "0.1.4", features = ["experimental"] }
rand = "0.8.5"

